const ProductsList = [
  {
    id: 1,
    category: 'Tradicional',
    name_product: 'Expresso Tradicional',
    description: 'O tradicional café feito com água quente e grãos moídos',
    price: 9.9,
    image: '../../src/assets/coffe/expresso.png',
    selected: false,
  },
  {
    id: 2,
    category: 'Tradicional',
    name_product: 'Expresso Americano',
    description: 'Expresso diluído, menos intenso que o tradicional',
    price: 9.9,
    image: '../../src/assets/coffe/americano.png',
    selected: false,
  },
  {
    id: 3,
    category: 'Tradicional',
    name_product: 'Expresso Cremoso',
    description: 'Café expresso tradicional com espuma cremosa',
    price: 9.9,
    image: '../../src/assets/coffe/expressoCremoso.png',
    selected: false,
  },
  {
    id: 4,
    category: 'Tradicional    Gelado',
    name_product: 'Expresso Gelado',
    description: 'Bebida preparada com café expresso e cubos de gelo',
    price: 9.9,
    image: '../../src/assets/coffe/cafeGelado.png',
    selected: false,
  },
  {
    id: 5,
    category: 'Tradicional com leite',
    name_product: 'Café com Leite',
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    price: 9.9,
    image: '../../src/assets/coffe/cafeLeite.png',
    selected: false,
  },
  {
    id: 6,
    category: 'Tradicional com leite',
    name_product: 'Latte',
    description:
      'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    price: 9.9,
    image: '../../src/assets/coffe/latte.png',
    selected: false,
  },
  {
    id: 7,
    category: 'Tradicional com leite',
    name_product: 'Capuccino',
    description:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    price: 9.9,
    image: '../../src/assets/coffe/capuccino.png',
    selected: false,
  },
  {
    id: 8,
    category: 'Tradicional com Leite',
    name_product: 'Macchiato',
    description:
      'Café expresso misturado com um pouco de leite quente e espuma',
    price: 9.9,
    image: '../../src/assets/coffe/macchiato.png',
    selected: false,
  },
  {
    id: 9,
    category: 'Tradicional com Leite',
    name_product: 'Mocaccino',
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    price: 9.9,
    image: '../../src/assets/coffe/mochaccino.png',
    selected: false,
  },
  {
    id: 10,
    category: 'Tradicional com Leite',
    name_product: 'Chocolate Quente',
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    price: 9.9,
    image: '../../src/assets/coffe/chocolateQuente.png',
    selected: false,
  },
  {
    id: 11,
    category: 'Especial | Alcoólico | Gelado',

    name_product: 'Cubano',
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    price: 9.9,
    image: '../../src/assets/coffe/mochaccino.png',
    selected: false,
  },
  {
    id: 12,
    category: 'Especial',
    name_product: 'Havaiano',
    description: 'Bebida adocicada preparada com café e leite de coco',
    price: 9.9,
    image: '../../src/assets/coffe/havaiano.png',
    selected: false,
  },
  {
    id: 13,
    category: 'Especial',
    name_product: 'Árabe',
    description: 'Bebida preparada com grãos de café árabe e especiarias',
    price: 9.9,
    image: '../../src/assets/coffe/arabe.png',
    selected: false,
  },
  {
    id: 14,
    category: 'Especial | Alcoólico',
    name_product: 'Irlandês',
    description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    price: 9.9,
    image: '../../src/assets/coffe/irlandes.png',
    selected: false,
  },
]

export default ProductsList
